export enum routes {
    Login = '/login',
    Home = '/app/home',
    Dashboard = '/app/dashboard',
    outComesTarget = "/app/outComesTarget",
    outComesAchievement = "/app/outComesAchievement",
    outComesReport = "/app/outComesReport",
    targetAchievementSummary = "/app/targetAchievementSummary",
    Reports = '/app/reports',
    ReportsOutcome = '/app/outcomeSummary',
    FocusDistrict = '/app/focusDistrict',
    // ComponentActivityMapping='/app/activityMaster/add',
    UtilizationCertificate = '/app/UtilizationCertificate/utilization',
    Activity = '/app/activityMaster',
    ActivityRevision = '/app/activityMasterRev',
    About = '/about',
    moreGallery = '/moreGallery',
    Objectives = '/objectives',
    InstitutionalStructure = '/institutionalStructure',
    Scope = '/scope',
    Components = '/components',
    Documents = '/document',
    Development = '/app/underDevelopment',
    HEIIdentification = '/app/underDevelopment',
    ComponentWiseMapping = '/app/component/componentMapping',
    ComponentList = '/app/component/componentList',
    StateProfileBasic = '/app/stateProfile/basic',
    populationData = '/app/stateProfile/populationData',
    highereducation = '/app/stateProfile/highereducation',
    NMDCDPR = '/app/dpr/newModelDegreeCollege',
    dprofile = '/app/districtProfile/basicdistrict',
    districteducation = '/app/districtProfile/districthighereducation',
    GSC = '/app/dpr/grantStrengthCollege',
    GSU = '/app/dpr/grantStrengthUniversity',
    gender = '/app/gender/preamble',
    collegeSection1 = '/app/dpr/strengthen/section1',
    collegeSection2 = '/app/dpr/strengthen/section2',
    collegeSection4 = '/app/dpr/strengthen/section4',
    collegeSection5 = '/app/dpr/strengthen/section5',
    nmdcSection1 = '/app/dpr/nmdCollege/nmdcSection1',
    nmdcSection2 = '/app/dpr/nmdCollege/nmdcSection2',
    nmdcSection5 = '/app/dpr/nmdCollege/nmdcSection5',
    nmdcSection6 = '/app/dpr/nmdCollege/nmdcSection6',
    nmdcSection7 = '/app/dpr/nmdCollege/nmdcSection7',
    nmdcSection11 = '/app/dpr/nmdCollege/nmdcSection11',    //Revision
    nmdcSection12 = '/app/dpr/nmdCollege/nmdcSection12',    //Revision
    nmdcSection15 = '/app/dpr/nmdCollege/nmdcSection15',    //Revision
    nmdcSection16 = '/app/dpr/nmdCollege/nmdcSection16',    //Revision
    nmdcSection17 = '/app/dpr/nmdCollege/nmdcSection17',    //Revision
    universitySection1 = '/app/dpr/strengthenUniversity/universitysection1',
    universitySection2 = '/app/dpr/strengthenUniversity/universitysection2',
    universitySection4 = '/app/dpr/strengthenUniversity/universitysection4',
    universitySection5 = '/app/dpr/strengthenUniversity/universitysection5',
    gieiSection1 = '/app/dpr/giei/gieiSection1',
    gieiSection3 = '/app/dpr/giei/gieiSection3',
    gieiSection4 = '/app/dpr/giei/gieiSection4',
    collegeSection11 = '/app/dpr/strengthen/section11',
    collegeSection12 = '/app/dpr/strengthen/section12',
    collegeSection14 = '/app/dpr/strengthen/section14',
    collegeSection14V3 = '/app/dpr/strengthen/section14V3',
    collegeSection15 = '/app/dpr/strengthen/section15',

    // upload = '/app/uploadMou',meruSectionPR5
    status = '/app/status',
    statusRevisionEquity = '/app/statusRevisionEquity',
    statusRevision = '/app/statusRevision',
    statusRevisionMeru = '/app/statusRevisionMeru',
    instituteList = '/app/component/instituteList',
    meruSection1 = '/app/dpr/meru/meruSection1',
    meruSection2 = '/app/dpr/meru/meruSection2',
    meruSection4 = '/app/dpr/meru/meruSection4',
    meruSection5 = '/app/dpr/meru/meruSection5',
    meruSectionpr1 = '/app/dpr/meru/meruSection11',
    meruSectionpr2 = '/app/dpr/meru/meruSection12',
    meruSectionpr4 = '/app/dpr/meru/meruSection14',
    meruSectionpr5 = '/app/dpr/meru/meruSection15',
    gieiSection11 = '/app/dpr/giei/gieiSection11',
    gieiSection13 = '/app/dpr/giei/gieiSection13',
    gieiSection14 = '/app/dpr/giei/gieiSection14',
    revisedDpr = '/app/dpr/dprRevised',
    statusDpr = '/app/dpr/dprRevisedStatus',

    //Re-Revision
    meruSectionV3 = '/app/dpr/meru/meruSectionV3',
    perposedCourseV3 = '/app/dpr/meru/perposedCourseV3',
    perposedOutcomeV3 = '/app/dpr/strengthen/perposedOutcomeV3',
    gieiSection13V3 = '/app/dpr/giei/gieiSection13V3',
    gieiOutcomeV3 = '/app/dpr/giei/gieiOutcomeV3',
    statusRevisionV3 = '/app/statusRevisionV3',




    npd = '/app/npd/stateprofilelist',
    viewState = '/app/npd/viewState',
    collegeList = '/app/npd/collegeList',
    universityList = '/app/npd/universityList',
    genderList = '/app/npd/genderList',
    meruList = '/app/npd/meruList',
    nmdcList = '/app/npd/nmdcList',

    stateprofilescrutiny = '/app/scrutiny/stateprofilescrutiny',
    collegescrutinylist = '/app/scrutiny/collegescrutinylist',
    universityscrutinylist = '/app/scrutiny/universityscrutinylist',
    meruscrutinylist = '/app/scrutiny/meruscrutinylist',
    genderscrutinylist = '/app/scrutiny/genderscrutinylist',
    nmdcscrutinylist = '/app/scrutiny/nmdcscrutinylist',

    collegepmushalistlock = '/app/pmprogresmonit/collegelocklist',
    projectItemTagg = '/app/pmprogresmonit/projectitemtag',
    collegepmushalist = '/app/pmprogresmonit/collegeprogresslist',
    universitypmushalist = '/app/pmprogresmonit/universityprogresslist',
    merupmushalist = '/app/pmprogresmonit/meruprogresslist',
    genderpmushalist = '/app/pmprogresmonit/genderprogresslist',
    nmdcpmushalist = '/app/pmprogresmonit/nmdcprogresslist',
    

    pmushalistRevision = '/app/pmprogresmonit/pmushalistRevision',
    pmushalistReRevision = '/app/pmprogresmonit/pmushalistReRevision',
    pmushaFinalApprove = '/app/pmprogresmonit/pmushalistApproved',
    collegepmushalistRevision = '/app/pmprogresmonit/collegeprogresslistRevision',
    universitypmushalistRevision = '/app/pmprogresmonit/universityprogresslistRevision',
    merupmushalistRevision = '/app/pmprogresmonit/meruprogresslistRevision',
    genderpmushalistRevision = '/app/pmprogresmonit/genderpmushalistRevision',
    nmdcpmushalistRevision = '/app/pmprogresmonit/nmdcpmushalistRevision',

    collegeProjectItemTag = '/app/pmprogresmonit/collegeProjectItemTag',
    universityProjectItemTag = '/app/pmprogresmonit/universityProjectItemTag',
    merupProjectItemTag = '/app/pmprogresmonit/merupProjectItemTag',
    genderProjectItemTag = '/app/pmprogresmonit/genderProjectItemTag',

    viewCollege = '/app/npd/view',
    viewReportDetails = '/app/npd/view',
    viewGenderEquity = '/app/npd/viewGenderEquity',
    consolidatedProposal = '/app/npd/consolidatedProposal',
    revisedConsolidatedProposal = '/app/npd/revisedConsolidatedProposal',
    dprConsolidatedProposal = '/app/npd/dprConsolidatedProposal',
    consolidatedProposalForworded = '/app/npd/consolidatedProposalForworded',
    rusaprogressmonitering = '/app/npd/rusaprogressmonitoring',
    rusaprogressupdation = '/app/npd/rusaprogressupdation',

    // scrutiny='/app/npd/scrutiny',
    logintrail = '/app/audit_log/login_trail',
    activitylog = '/app/audit_log/activity_log',


    viewinstCollege = '/app/ipmr/viewIns',
    viewinstUniver = '/app/ipmr/viewUniv',
    viewinstMeru = '/app/ipmr/viewMeru',
    viewinstNMDC = '/app/ipmr/viewNmdc',
    viewinsGenderEquity = '/app/ipmr/viewinsGenderEquity',

    viewIpmr = '/app/ipmr',
    viewinstCollegeLock = '/app/ipmr/viewInsLock',
    viewinstCollegeLock1 = '/app/ipmr/viewInsLock1',
    viewinstUniverLock = '/app/ipmr/viewUnivLock',
    viewinstMeruLock = '/app/ipmr/viewMeruLock',
    viewinstGenderLock = '/app/ipmr/viewGenderLock',

    viewinstProjectTag = '/app/ipmr/viewInsProjectTag',
    viewinstUniverProjectTag = '/app/ipmr/viewUnivProjectTag',
    viewinstMeruProjectTag = '/app/ipmr/viewMeruProjectTag',
    viewinstGenderProjectTag = '/app/ipmr/viewGenderProjectTag',
    viewReportProjectTag = '/app/ipmr/viewReportProjectTag',
    viewReportUniverProjectTag = '/app/ipmr/viewReportUnivProjectTag',
    viewReportMeruProjectTag = '/app/ipmr/viewReportMeruProjectTag',
    viewReportGenderProjectTag = '/app/ipmr/viewReportGenderProjectTag',


    viewStrengthenRevision = '/app/proposalrevision/viewStrenthRevision',
    viewStrengthenRevisionApp = '/app/proposalrevision/viewStrenthRevisionApp',
    viewMeruCollegeUniversityRevisionV3 = '/app/proposalrevision/viewMeruCollegeUniversityRevisionV3',
    viewMeruCollegeUniversityRevisionAppV3 = '/app/proposalrevision/viewMeruCollegeUniversityRevisionAppV3',
    viewEquityNMDCRevisionV3 = '/app/proposalrevision/viewEquityNMDCRevisionV3',
    viewEquityNMDCRevisionAppV3 = '/app/proposalrevision/viewEquityNMDCRevisionAppV3',
    viewMeruRevision = '/app/proposalrevision/viewMeruRevision',
    viewMeruRevisionApp = '/app/proposalrevision/viewMeruRevisionApp',
    viewEquityRevision = '/app/proposalrevision/viewEquityRevision',
    viewEquityRevisionApp = '/app/proposalrevision/viewEquityRevisionApp',
    viewNMDCRevision = '/app/proposalrevision/viewNMDCRevision',
    viewNMDCRevisionApp = '/app/proposalrevision/viewNMDCRevisionApp',

    viewReportTagRevision = '/app/reports/viewReportTagRevision',
    viewReportStrengthenRevision = '/app/reports/viewReportStrenthRevision',
    viewReportMeruRevision = '/app/reports/viewReportMeruRevision',
    viewReportEquityRevision = '/app/reports/viewReportEquityRevision',
    viewReportStrengthenRevisionAch = '/app/reports/viewReportStrenthRevisionAch',
    viewReportMeruRevisionAch = '/app/reports/viewReportMeruRevisionAch',
    viewReportEquityRevisionAch = '/app/reports/viewReportEquityRevisionAch',
    viewOutcomeStrengthenRevision = '/app/outcomeSummary/viewOutcomeStrenthRevision',
    viewOutcomeMeruRevision = '/app/outcomeSummary/viewOutcomeMeruRevision',
    viewOutcomeEquityRevision = '/app/outcomeSummary/viewOutcomeEquityRevision',
    viewOutcomeStrengthenRevisionAch = '/app/outcomeSummary/viewOutcomeStrenthRevisionAch',
    viewOutcomeMeruRevisionAch = '/app/outcomeSummary/viewOutcomeMeruRevisionAch',
    viewOutcomeEquityRevisionAch = '/app/outcomeSummary/viewOutcomeEquityRevisionAch',
    viewReport = '/app/reports/viewReport',





    home = '/home',
    viewMoU = '/app/uploadMou/viewMoU',
    upload = '/app/uploadMou/upload',
    emailManagementSubmit='/app/emailManagement/emailManagementSubmit',
    documentUpload = '/app/documentUpload',
    sanctionModel = '/app/sanctionModel',
    stateIssueModel = '/app/stateIssueModel',
    fundManagement = '/app/fundManagement',
    FUNDDEMAND = '/app/fundManagement/fundDemand',
    // proposalrevision ='/app/proposalrevision',
    addUser = '/app/usermanagement/add',
    addUser1 = '/app/usermanagement/add1',
    addUserU = '/app/usermanagement/addUno/',
    addUserC = '/app/usermanagement/addCno/',
    addUserT = '/app/usermanagement/addTsg',
    addUserO = '/app/usermanagement/addUserO',
    addSAA = '/app/usermanagement/addsaa',
    addUserSPD = '/app/usermanagement/addspd',
    viewUser = '/app/usermanagement/view',

    addTsgCheif = '/app/usermanagement/addtsgcheif',
    addTsg = '/app/usermanagement/addtsg',

    editUser = '/app/usermanagement/edit',
    changePass = '/app/changePassword',
    underDevelopment = '/app/underDevelopment',
    viewNmdc = '/app/npd/viewNmdc',
    viewMmer = '/app/npd/viewMmer',
    viewMeru = '/app/npd/viewMeru',
    rusaLegacy = '/app/stateProfile/rusaLegacy',
    verifyUser = '/verifyUser',
    forgot = '/forgot',
    help = '/help',
    forword = '/app/npd/forword',
    addSAANone = '/app/usermanagement/addsaaNone',
    addSPD = '/app/usermanagement/addspd',
    addRUSA = '/app/usermanagement/addrusa',
    statusNoteManagment = '/app/statusnotemanagment',
    statusNote = '/app/statusnotemanagment/statusNote',
    eventsManagement1 = '/app/eventsManagement'


}
